name       = "forsolver"
version    = "0.3.1"
author     = "Seyed Ali Ghasemi"
maintainer = "info@gha3mi.com"
copyright  = "Copyright (c) 2023, Seyed Ali Ghasemi"
license    = "BSD-3"

[build]
auto-executables = false
auto-tests       = false
auto-examples    = false
module-naming    = false

[install]
library = true

[fortran]
implicit-typing   = false
implicit-external = false
source-form       = "free"

[dependencies]
kinds       = {git="https://github.com/gha3mi/kinds.git"}
fordiff     = {git="https://github.com/gha3mi/fordiff.git"}
forunittest = {git="https://github.com/gha3mi/forunittest.git"}

[[test]]
name       = "test_solver1"
source-dir = "test"
main       = "test_solver1.f90"

[[test]]
name       = "test_solver2"
source-dir = "test"
main       = "test_solver2.f90"

[[test]]
name       = "test_solver3"
source-dir = "test"
main       = "test_solver3.f90"

[[test]]
name       = "test_solver4"
source-dir = "test"
main       = "test_solver4.f90"

[[test]]
name       = "test_solver5"
source-dir = "test"
main       = "test_solver5.f90"

[[test]]
name       = "test_solver6"
source-dir = "test"
main       = "test_solver6.f90"

[[test]]
name       = "test_solver7"
source-dir = "test"
main       = "test_solver7.f90"

[[test]]
name       = "test_solver8"
source-dir = "test"
main       = "test_solver8.f90"

[[test]]
name       = "test_solver9"
source-dir = "test"
main       = "test_solver9.f90"

[[test]]
name       = "test_solver10"
source-dir = "test"
main       = "test_solver10.f90"

[[test]]
name       = "test_solver11"
source-dir = "test"
main       = "test_solver11.f90"

[[test]]
name       = "test_solver12"
source-dir = "test"
main       = "test_solver12.f90"

[[test]]
name       = "test_solver13"
source-dir = "test"
main       = "test_solver13.f90"

[[test]]
name       = "test_solver14"
source-dir = "test"
main       = "test_solver14.f90"

[[test]]
name       = "test_solver15"
source-dir = "test"
main       = "test_solver15.f90"

[[test]]
name       = "test_solver16"
source-dir = "test"
main       = "test_solver16.f90"

[[test]]
name       = "test_solver17"
source-dir = "test"
main       = "test_solver17.f90"
