project:             forsolver
version:             v0.1.0
year:                2023
project_github:      https://github.com/gha3mi/forsolver
author:              Seyed Ali Ghasemi
email:               info@gha3mi.com
github:              https://github.com/gha3mi
src_dir:             ./src
output_dir:          ./doc
source:              true
graph:               true
coloured_edges:      true
search:              true
display:             public
                     private
                     protected
print_creation_date: true

