gesv_rel – ForSolver
gesv_rel Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
24 statements
Source File
private pure subroutine gesv_rel(A, b, x, info)
Uses
external_interfaces_solver
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:, :), contiguous :: A
real(kind=rk), intent(in), dimension(:), contiguous :: b
real(kind=rk), intent(out), dimension(max(1, size(A, 2))) :: x
integer, intent(out) :: info
Calls
Called by
Source Code
   pure subroutine gesv_rel(A, b, x, info)
      use external_interfaces_solver, only: gesv
      ! inputs:
      real(rk), dimension(:, :), contiguous, intent(in) :: A    ! input matrix A
      real(rk), dimension(:),    contiguous, intent(in) :: b    ! right-hand side matrix b
      ! outputs:
      real(rk), dimension(max(1, size(A, 2))), intent(out) :: x    ! solution matrix x
      integer,                                 intent(out) :: info ! result info
      ! local variables
      integer                               :: n, lda, ldb, nrhs
      integer,  dimension(size(A, 2))       :: ipiv
      real(rk), dimension(:,:), allocatable :: a_copy
      real(rk), dimension(:,:), allocatable :: b_copy
      ! get dimensions
      nrhs = 1 ! size(b, 2)
      n    = size(A, 2)
      lda  = max(1, n)
      ldb  = max(1, n)
      ! copy the input matrices
      a_copy = a
      allocate(b_copy(ldb, nrhs))
      b_copy(:, 1) = b
      ! call gels subroutine
      call gesv(n, nrhs, a_copy, lda, ipiv, b_copy, ldb, info)
      ! copy the solution matrix
      if (info == 0) then
         x = b_copy(1:ldb, 1) ! nrhs = 1
      else
         error stop 'gesv failed'
      end if
   end subroutine gesv_rel
Call graph
gesv_rel calls gesv
solver_lin calls gesv_rel
solve calls solver_lin
modified_newton_method_t1 calls solve
modified_quasi_cs_newton_method_t1 calls solve
modified_quasi_fd_newton_method_t1 calls solve
newton_method_t1 calls solve
quasi_cs_newton_method_t1 calls solve
quasi_fd_newton_method_t1 calls solve
test_solver1 calls solve
test_solver15 calls solve
test_solver16 calls solve
test_solver17 calls solve
test_solver2 calls solve
newton_complex_step_rel_t1 calls modified_quasi_cs_newton_method_t1, quasi_cs_newton_method_t1
newton_rel_t1 calls modified_newton_method_t1, modified_quasi_fd_newton_method_t1, newton_method_t1, quasi_fd_newton_method_t1
test_solver10 calls solve
test_solver11 calls solve
test_solver12 calls solve
test_solver13 calls solve
test_solver14 calls solve
test_solver3 calls solve
test_solver4 calls solve
test_solver5 calls solve
test_solver6 calls solve
test_solver7 calls solve
test_solver8 calls solve
test_solver9 calls solve