modified_quasi_cs_newton_method_T1 – ForSolver
modified_quasi_cs_newton_method_T1 Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
43 statements
Source File
private impure subroutine modified_quasi_cs_newton_method_T1(this, F, x0, x_sol)
Arguments
Type Intent Optional Attributes Name
class(nlsolver), intent(inout) :: this
procedure(Fun17) :: F
complex(kind=rk), intent(in), dimension(:) :: x0
complex(kind=rk), intent(out), dimension(size(x0)) :: x_sol
Calls
Called by
Source Code
   impure subroutine modified_quasi_cs_newton_method_T1(this, F, x0,  x_sol)
      interface
         impure function Fun17(x) result(res)
            import rk
            implicit none
            complex(rk), dimension(:), intent(in)  :: x
            complex(rk), dimension(:), allocatable :: res
         end function Fun17
      end interface
      procedure(Fun17)  :: F
      class(nlsolver),                  intent(inout) :: this
      complex(rk), dimension(:),        intent(in)    :: x0
      complex(rk), dimension(size(x0)), intent(out)   :: x_sol
      complex(rk), dimension(size(x0))                :: xk
      complex(rk), dimension(:),   allocatable        :: F_val
      real(rk),    dimension(:,:), allocatable        :: dFdx_val
      real(rk)                                        :: criteriaFun
      integer                                         :: k
      logical                                         :: convergenz
      real(rk), dimension(size(x0))                   :: dk
      real(rk)                                        :: alphak
      k          = 0
      xk         = x0
      convergenz = .false.
      do while (.not. convergenz .and. k < this%maxit)
         F_val    = F(xk)
         if (mod(k, this%nmp) == 0) dFdx_val = derivative(f=F, x=real(xk,kind=rk), h=this%cs_tol)
         criteriaFun = norm2(real(F_val, kind=rk))
         if (this%verbosity == 1) then
            print '(g0, e12.4)', k, criteriaFun
         end if
         if (criteriaFun <= this%TolFun) then
            convergenz = .true.
            x_sol      = xk
            return
         else
            dk = - solve(dFdx_val, real(F_val, kind=rk), this%lin_method)
            alphak = 1.0_rk
            xk = xk + alphak*dk
            k = k + 1
         end if
      end do
   end subroutine modified_quasi_cs_newton_method_T1
Call graph
modified_quasi_cs_newton_method_t1 calls derivative, solve
solve calls solver_lin
solver_lin calls gels_rel, gesv_rel
gels_rel calls gels
gesv_rel calls gesv
newton_complex_step_rel_t1 calls modified_quasi_cs_newton_method_t1
test_solver10 calls solve
test_solver11 calls solve
test_solver12 calls solve
test_solver13 calls solve
test_solver14 calls solve
test_solver3 calls solve
test_solver4 calls solve
test_solver5 calls solve
test_solver6 calls solve
test_solver7 calls solve
test_solver8 calls solve
test_solver9 calls solve