modified_quasi_fd_newton_method_T0 – ForSolver
modified_quasi_fd_newton_method_T0 Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
45 statements
Source File
private impure subroutine modified_quasi_fd_newton_method_T0(this, F, x0, x_sol)
Arguments
Type Intent Optional Attributes Name
class(nlsolver), intent(inout) :: this
procedure(Fun8) :: F
real(kind=rk), intent(in) :: x0
real(kind=rk), intent(out) :: x_sol
Calls
Called by
Source Code
   impure subroutine modified_quasi_fd_newton_method_T0(this, F, x0,  x_sol)
      interface
         impure function Fun8(x) result(res)
            import rk
            implicit none
            real(rk), intent(in) :: x
            real(rk)             :: res
         end function Fun8
      end interface
      procedure(Fun8) :: F
      class(nlsolver), intent(inout) :: this
      real(rk),        intent(in)    :: x0
      real(rk),        intent(out)   :: x_sol
      real(rk)                       :: xk
      real(rk)                       :: F_val
      real(rk)                       :: dFdx_val
      real(rk)                       :: criteriaFun
      integer                        :: k
      logical                        :: convergenz
      real(rk)                       :: pk
      real(rk)                       :: qk
      real(rk)                       :: dk
      real(rk)                       :: alphak
      k          = 0
      xk         = x0
      convergenz = .false.
      do while (.not. convergenz .and. k < this%maxit)
         F_val = F(xk)
         if (mod(k, this%nmp) == 0) dFdx_val = derivative(f=F, x=xk, h=this%fdm_tol, method=this%fdm_method)
         criteriaFun = abs(F_val)
         if (this%verbosity == 1) then
            print '(g0, f12.4, 4x, e12.4, 4x, e12.4)', k, xk, F_val, dFdx_val
         end if
         if (criteriaFun <= this%TolFun) then
            convergenz = .true.
            x_sol      = xk
            return
         else
            dk = - F_val / dFdx_val
            alphak = 1.0_rk
            xk = xk + alphak*dk
            k = k + 1
         end if
      end do
   end subroutine modified_quasi_fd_newton_method_T0
Call graph
modified_quasi_fd_newton_method_t0 calls derivative
newton_rel_t0 calls modified_quasi_fd_newton_method_t0
test_solver10 calls solve
test_solver11 calls solve
test_solver12 calls solve
test_solver13 calls solve
test_solver14 calls solve
test_solver3 calls solve
test_solver4 calls solve
test_solver5 calls solve
test_solver6 calls solve
test_solver7 calls solve
test_solver8 calls solve
test_solver9 calls solve