newton_rel_T0 – ForSolver
newton_rel_T0 Subroutine
Seyed Ali Ghasemi
BSD 3-Clause
46 statements
Source File
private impure subroutine newton_rel_T0(this, F, dFdx, x0, x_sol)
Type Bound
nlsolver
Arguments
Type Intent Optional Attributes Name
class(nlsolver), intent(inout) :: this
procedure(Fun1) :: F
procedure(dFun1), optional :: dFdx
real(kind=rk), intent(in) :: x0
real(kind=rk), intent(out) :: x_sol
Calls
Called by
Source Code
   impure subroutine newton_rel_T0(this, F, dFdx, x0,  x_sol)
      interface
         impure function Fun1(x)
            import rk
            implicit none
            real(rk), intent(in) :: x
            real(rk)             :: Fun1
         end function Fun1
         impure function dFun1(x)
            import rk
            implicit none
            real(rk), intent(in) :: x
            real(rk)             :: dFun1
         end function dFun1
      end interface
      procedure(Fun1)            :: F
      procedure(dFun1), optional :: dFdx
      class(nlsolver), intent(inout) :: this
      real(rk),        intent(in)    :: x0
      real(rk),        intent(out)   :: x_sol
      if (this%verbosity == 1) then
         print '(a)', '-----------------------------------------------'
         print '(a)', 'maxit             x0                   tol'
         print '(g0, 10x, f12.8, 10x, e12.4)', this%maxit, x0, this%TolFun
         print '(a)', '-----------------------------------------------'
         print '(a)', 'start newton'
         print '(a)', '-----------------------------------------------'
         print '(a)', 'it        xn           F(xn)         dF(xn)/dxn'
      end if
      select case (this%nl_method)
       case ('newton')
         call newton_method_T0(this, F, dFdx, x0,  x_sol)
       case ('newton-modified')
         call modified_newton_method_T0(this, F, dFdx, x0,  x_sol)
       case ('newton-quasi-fd')
         call quasi_fd_newton_method_T0(this, F, x0,  x_sol)
       case ('newton-quasi-fd-modified')
         call modified_quasi_fd_newton_method_T0(this, F, x0,  x_sol)
         !  case ('newton-quasi-bfgs')
         !    call quasi_bfgs_newton_method_T0(this, F, x0,  x_sol)
         !  case ('newton-quasi-bfgs-modified')
         !    call modified_quasi_bfgs_newton_method_T0(this, F, x0,  x_sol)
      end select
      if (this%verbosity == 1) then
         print '(a)', '-----------------------------------------------'
         print '(a)', 'end newton'
         print '(a)', '-----------------------------------------------'
         print '(a, g0)', 'x_sol = ', x_sol
      end if
   end subroutine newton_rel_T0
Call graph
newton_rel_t0 calls modified_newton_method_t0, modified_quasi_fd_newton_method_t0, newton_method_t0, quasi_fd_newton_method_t0
modified_quasi_fd_newton_method_t0 calls derivative
quasi_fd_newton_method_t0 calls derivative
test_solver10 calls solve
test_solver11 calls solve
test_solver12 calls solve
test_solver13 calls solve
test_solver14 calls solve
test_solver3 calls solve
test_solver4 calls solve
test_solver5 calls solve
test_solver6 calls solve
test_solver7 calls solve
test_solver8 calls solve
test_solver9 calls solve