newton_method_T0 – ForSolver
newton_method_T0 Subroutine
Seyed Ali Ghasemi
50 statements
Source File
private impure subroutine newton_method_T0(this, F, dFdx, x0, x_sol)
Arguments
Type Intent Optional Attributes Name
class(nlsolver), intent(inout) :: this
procedure(Fun5) :: F
procedure(dFun5) :: dFdx
real(kind=rk), intent(in) :: x0
real(kind=rk), intent(out) :: x_sol
Called by
Source Code
   impure subroutine newton_method_T0(this, F, dFdx, x0,  x_sol)
      interface
         impure function Fun5(x) result(res)
            import rk
            implicit none
            real(rk), intent(in)  :: x
            real(rk) :: res
         end function Fun5
         impure function dFun5(x) result(res)
            import rk
            implicit none
            real(rk), intent(in)    :: x
            real(rk) :: res
         end function dFun5
      end interface
      procedure(Fun5)  :: F
      procedure(dFun5) :: dFdx
      class(nlsolver), intent(inout) :: this
      real(rk),        intent(in)    :: x0
      real(rk),        intent(out)   :: x_sol
      real(rk)                       :: xk
      real(rk)                       :: F_val
      real(rk)                       :: dFdx_val
      real(rk)                       :: criteriaFun
      integer                        :: k
      logical                        :: convergenz
      real(rk)                       :: dk
      real(rk)                       :: alphak
      k          = 0
      xk         = x0
      convergenz = .false.
      do while (.not. convergenz .and. k < this%maxit)
         F_val = F(xk)
         dFdx_val = dFdx(xk)
         criteriaFun = abs(F_val)
         if (this%verbosity == 1) then
            print '(g0, f12.4, 4x, e12.4, 4x, e12.4)', k, xk, F_val, dFdx_val
         end if
         if (criteriaFun <= this%TolFun) then
            convergenz = .true.
            x_sol      = xk
            return
         else
            dk = - F_val / dFdx_val
            alphak = 1.0_rk
            xk = xk + alphak*dk
            k = k + 1
         end if
      end do
   end subroutine newton_method_T0
Call graph
newton_rel_t0 calls newton_method_t0
test_solver10 calls solve
test_solver11 calls solve
test_solver12 calls solve
test_solver13 calls solve
test_solver14 calls solve
test_solver3 calls solve
test_solver4 calls solve
test_solver5 calls solve
test_solver6 calls solve
test_solver7 calls solve
test_solver8 calls solve
test_solver9 calls solve