solver_lin – ForSolver
solver_lin Function
Seyed Ali Ghasemi
21 statements
Source File
private pure function solver_lin(A, b, method) result(x)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:, :), contiguous :: A
real(kind=rk), intent(in), dimension(:), contiguous :: b
character(len=*), intent(in), optional :: method
Return Value real(kind=rk), dimension(max(1, size(A, 2)))
Calls
Called by
Source Code
   pure function solver_lin(A, b, method) result(x)
      ! inputs
      real(rk),     dimension(:, :), contiguous, intent(in) :: A      ! input matrix A
      real(rk),     dimension(:),    contiguous, intent(in) :: b      ! right-hand side matrix b
      character(*), optional,                    intent(in) :: method
      ! outputs:
      real(rk), dimension(max(1, size(A, 2))) :: x      ! solution matrix x
      ! local variables
      integer :: info ! result info
      ! call solver
      if (present(method)) then
         select case (method)
          case ('gesv')
            call gesv_rel(A, b, x, info)
          case ('gels')
            call gels_rel(A, b, x, info)
         end select
      else
         if (size(A,1)==size(A,2)) then
            call gesv_rel(A, b, x, info)
         else
            call gels_rel(A, b, x, info)
         end if
      end if
   end function solver_lin
Call graph
solver_lin calls gels_rel, gesv_rel
gels_rel calls gels
gesv_rel calls gesv
solve calls solver_lin
modified_newton_method_t1 calls solve
modified_quasi_cs_newton_method_t1 calls solve
modified_quasi_fd_newton_method_t1 calls solve
newton_method_t1 calls solve
quasi_cs_newton_method_t1 calls solve
quasi_fd_newton_method_t1 calls solve
test_solver1 calls solve
test_solver15 calls solve
test_solver16 calls solve
test_solver17 calls solve
test_solver2 calls solve
newton_complex_step_rel_t1 calls modified_quasi_cs_newton_method_t1, quasi_cs_newton_method_t1
newton_rel_t1 calls modified_newton_method_t1, modified_quasi_fd_newton_method_t1, newton_method_t1, quasi_fd_newton_method_t1
test_solver10 calls solve
test_solver11 calls solve
test_solver12 calls solve
test_solver13 calls solve
test_solver14 calls solve
test_solver3 calls solve
test_solver4 calls solve
test_solver5 calls solve
test_solver6 calls solve
test_solver7 calls solve
test_solver8 calls solve
test_solver9 calls solve