gels – forsolver
gels Interface
26 statements
Source File
public interface gels
Called by
Subroutines
public pure subroutine dgels(ftrans, fm, fn, fnrhs, fa, flda, fb, fldb, fwork, flwork, finfo)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: ftrans
integer, intent(in) :: fm
integer, intent(in) :: fn
integer, intent(in) :: fnrhs
real(kind=rk), intent(inout) :: fa(flda,*)
integer, intent(in) :: flda
real(kind=rk), intent(inout) :: fb(fldb,*)
integer, intent(in) :: fldb
real(kind=rk), intent(in) :: fwork(*)
integer, intent(in) :: flwork
integer, intent(out) :: finfo
public pure subroutine sgels(ftrans, fm, fn, fnrhs, fa, flda, fb, fldb, fwork, flwork, finfo)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: ftrans
integer, intent(in) :: fm
integer, intent(in) :: fn
integer, intent(in) :: fnrhs
real(kind=rk), intent(inout) :: fa(flda,*)
integer, intent(in) :: flda
real(kind=rk), intent(inout) :: fb(fldb,*)
integer, intent(in) :: fldb
real(kind=rk), intent(in) :: fwork(*)
integer, intent(in) :: flwork
integer, intent(out) :: finfo
public pure subroutine dgels(ftrans, fm, fn, fnrhs, fa, flda, fb, fldb, fwork, flwork, finfo)
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: ftrans
integer, intent(in) :: fm
integer, intent(in) :: fn
integer, intent(in) :: fnrhs
real(kind=rk), intent(inout) :: fa(flda,*)
integer, intent(in) :: flda
real(kind=rk), intent(inout) :: fb(fldb,*)
integer, intent(in) :: fldb
real(kind=rk), intent(in) :: fwork(*)
integer, intent(in) :: flwork
integer, intent(out) :: finfo
Call graph
gels_rel calls gels
solver_lin calls gels_rel
solve calls solver_lin
modified_newton_method_t1 calls solve
modified_quasi_cs_newton_method_t1 calls solve
modified_quasi_fd_newton_method_t1 calls solve
newton_method_t1 calls solve
quasi_cs_newton_method_t1 calls solve
quasi_fd_newton_method_t1 calls solve
newton_complex_step_rel_t1 calls modified_quasi_cs_newton_method_t1, quasi_cs_newton_method_t1
newton_rel_t1 calls modified_newton_method_t1, modified_quasi_fd_newton_method_t1, newton_method_t1, quasi_fd_newton_method_t1