gesv – ForSolver
gesv Interface
26 statements
Source File
public interface gesv
Called by
Subroutines
public pure subroutine dgesv(fn, fnrhs, fa, flda, fipiv, fb, fldb, finfo)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fn
integer, intent(in) :: fnrhs
real(kind=rk), intent(inout) :: fa(flda,fn)
integer, intent(in) :: flda
integer, intent(out) :: fipiv(fn)
real(kind=rk), intent(inout) :: fb(fldb,fnrhs)
integer, intent(in) :: fldb
integer, intent(out) :: finfo
public pure subroutine sgesv(fn, fnrhs, fa, flda, fipiv, fb, fldb, finfo)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fn
integer, intent(in) :: fnrhs
real(kind=rk), intent(inout) :: fa(flda,fn)
integer, intent(in) :: flda
integer, intent(out) :: fipiv(fn)
real(kind=rk), intent(inout) :: fb(fldb,fnrhs)
integer, intent(in) :: fldb
integer, intent(out) :: finfo
public pure subroutine dgesv(fn, fnrhs, fa, flda, fipiv, fb, fldb, finfo)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fn
integer, intent(in) :: fnrhs
real(kind=rk), intent(inout) :: fa(flda,fn)
integer, intent(in) :: flda
integer, intent(out) :: fipiv(fn)
real(kind=rk), intent(inout) :: fb(fldb,fnrhs)
integer, intent(in) :: fldb
integer, intent(out) :: finfo
Call graph
gesv_rel calls gesv
solver_lin calls gesv_rel
solve calls solver_lin
modified_newton_method_t1 calls solve
modified_quasi_cs_newton_method_t1 calls solve
modified_quasi_fd_newton_method_t1 calls solve
newton_method_t1 calls solve
quasi_cs_newton_method_t1 calls solve
quasi_fd_newton_method_t1 calls solve
test_solver1 calls solve
test_solver15 calls solve
test_solver16 calls solve
test_solver17 calls solve
test_solver2 calls solve
newton_complex_step_rel_t1 calls modified_quasi_cs_newton_method_t1, quasi_cs_newton_method_t1
newton_rel_t1 calls modified_newton_method_t1, modified_quasi_fd_newton_method_t1, newton_method_t1, quasi_fd_newton_method_t1
test_solver10 calls solve
test_solver11 calls solve
test_solver12 calls solve
test_solver13 calls solve
test_solver14 calls solve
test_solver3 calls solve
test_solver4 calls solve
test_solver5 calls solve
test_solver6 calls solve
test_solver7 calls solve
test_solver8 calls solve
test_solver9 calls solve