solve – ForSolver
solve Interface
BSD 3-Clause
3 statements
Source File
public interface solve
Calls
Called by
Module Procedures
private pure function solver_lin(A, b, method) result(x)
Author
Seyed Ali Ghasemi
License
BSD 3-Clause
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:, :), contiguous :: A
real(kind=rk), intent(in), dimension(:), contiguous :: b
character(len=*), intent(in), optional :: method
Return Value real(kind=rk), dimension(max(1, size(A, 2)))
Call graph
solve calls solver_lin
solver_lin calls gels_rel, gesv_rel
gels_rel calls gels
gesv_rel calls gesv
modified_newton_method_t1 calls solve
modified_quasi_cs_newton_method_t1 calls solve
modified_quasi_fd_newton_method_t1 calls solve
newton_method_t1 calls solve
quasi_cs_newton_method_t1 calls solve
quasi_fd_newton_method_t1 calls solve
test_solver1 calls solve
test_solver15 calls solve
test_solver16 calls solve
test_solver17 calls solve
test_solver2 calls solve
newton_complex_step_rel_t1 calls modified_quasi_cs_newton_method_t1, quasi_cs_newton_method_t1
newton_rel_t1 calls modified_newton_method_t1, modified_quasi_fd_newton_method_t1, newton_method_t1, quasi_fd_newton_method_t1
test_solver10 calls solve
test_solver11 calls solve
test_solver12 calls solve
test_solver13 calls solve
test_solver14 calls solve
test_solver3 calls solve
test_solver4 calls solve
test_solver5 calls solve
test_solver6 calls solve
test_solver7 calls solve
test_solver8 calls solve
test_solver9 calls solve