test_solver4 – ForSolver
test_solver4 Program
14 statements
Source File
Uses
forunittest
my_function4
forsolver
kinds
Calls
Variables
Type Attributes Name Initial
type(nlsolver) :: nls
real(kind=rk) :: x
real(kind=rk) :: expected_x
type(unit_test) :: ut
Source Code
program test_solver4
   use kinds, only: rk
   use forsolver, only: nlsolver
   use my_function4, only: F1, dF1dx
   use forunittest, only: unit_test
   implicit none
   type(nlsolver) :: nls
   real(rk)       :: x, expected_x
   type(unit_test) :: ut
   call nls%set_options(&
      nl_method   = 'newton-modified',&
      nmp         = 2,&
      maxit       = 100,&
      TolFun      = 1e-4_rk,&
      verbosity   = 0)
   call nls%solve(F=F1, dFdx=dF1dx, x0=10.0_rk, x_sol=x)
   ! check if solution is close to ~=0.53128
   expected_x = 0.53128_rk
   call ut%check(x, expected_x, 1.0e-4_rk, 'test_solver4' )
end program test_solver4
Call graph
test_solver4 calls check, solve, set_options
newton_complex_step_rel_t0 calls modified_quasi_cs_newton_method_t0, quasi_cs_newton_method_t0
newton_complex_step_rel_t1 calls modified_quasi_cs_newton_method_t1, quasi_cs_newton_method_t1
newton_rel_t0 calls modified_newton_method_t0, modified_quasi_fd_newton_method_t0, newton_method_t0, quasi_fd_newton_method_t0
newton_rel_t1 calls modified_newton_method_t1, modified_quasi_fd_newton_method_t1, newton_method_t1, quasi_fd_newton_method_t1
modified_newton_method_t1 calls solve
modified_quasi_cs_newton_method_t0 calls derivative
modified_quasi_cs_newton_method_t1 calls derivative, solve
modified_quasi_fd_newton_method_t0 calls derivative
modified_quasi_fd_newton_method_t1 calls derivative, solve
newton_method_t1 calls solve
quasi_cs_newton_method_t0 calls derivative
quasi_cs_newton_method_t1 calls derivative, solve
quasi_fd_newton_method_t0 calls derivative
quasi_fd_newton_method_t1 calls derivative, solve
solve calls solver_lin
solver_lin calls gels_rel, gesv_rel
gels_rel calls gels
gesv_rel calls gesv