test_solver12 – ForSolver
test_solver12 Program
13 statements
Source File
Uses
forsolver
my_function12
forunittest
Calls
Variables
Type Attributes Name Initial
type(nlsolver) :: nls
real(kind=rk), dimension(2) :: x
real(kind=rk), dimension(2) :: expected_x
type(unit_test) :: ut
Source Code
program test_solver12
   use forsolver
   use my_function12
   use forunittest
   implicit none
   type(nlsolver)         :: nls
   real(rk), dimension(2) :: x, expected_x
   type(unit_test) :: ut
   call nls%set_options(&
      nl_method   = 'newton-quasi-fd-modified',&
      fdm_method  = 'central',&
      fdm_tol     = 1e-7_rk,&
      nmp         = 1,&
      maxit       = 1000,&
      TolFun      = 1e-2_rk,&
      verbosity   = 0)
   call nls%solve(F=F3, x0=[0.95_rk,0.95_rk], x_sol=x)
   ! check if solution is close to [1,1]
   expected_x = [1.0_rk,1.0_rk]
   call ut%check(x, expected_x, 1.0e-1_rk, 'test_solver12' )
end program test_solver12
Call graph
test_solver12 calls check, solve, set_options
newton_complex_step_rel_t0 calls modified_quasi_cs_newton_method_t0, quasi_cs_newton_method_t0
newton_complex_step_rel_t1 calls modified_quasi_cs_newton_method_t1, quasi_cs_newton_method_t1
newton_rel_t0 calls modified_newton_method_t0, modified_quasi_fd_newton_method_t0, newton_method_t0, quasi_fd_newton_method_t0
newton_rel_t1 calls modified_newton_method_t1, modified_quasi_fd_newton_method_t1, newton_method_t1, quasi_fd_newton_method_t1
modified_newton_method_t1 calls solve
modified_quasi_cs_newton_method_t0 calls derivative
modified_quasi_cs_newton_method_t1 calls derivative, solve
modified_quasi_fd_newton_method_t0 calls derivative
modified_quasi_fd_newton_method_t1 calls derivative, solve
newton_method_t1 calls solve
quasi_cs_newton_method_t0 calls derivative
quasi_cs_newton_method_t1 calls derivative, solve
quasi_fd_newton_method_t0 calls derivative
quasi_fd_newton_method_t1 calls derivative, solve
solve calls solver_lin
solver_lin calls gels_rel, gesv_rel
gels_rel calls gels
gesv_rel calls gesv