test_solver14 – ForSolver
test_solver14 Program
BSD 3-Clause
15 statements
Source File
Uses
my_function14
forsolver
forunittest
forsolver_kinds
Calls
Variables
Type Attributes Name Initial
real(kind=rk), dimension(2) :: expected_x
type(nlsolver) :: nls
type(unit_test) :: ut
complex(kind=rk), dimension(2) :: x
Source Code
program test_solver14
   use forsolver_kinds, only: rk
   use forsolver, only: nlsolver
   use my_function14, only: F4
   use forunittest, only: unit_test
   implicit none
   type(nlsolver)            :: nls
   complex(rk), dimension(2) :: x
   real(rk),    dimension(2) :: expected_x
   type(unit_test) :: ut
   call nls%set_options(&
      nl_method   = 'newton-quasi-cs-modified',&
      cs_tol      = tiny(0.0_rk),&
      nmp         = 1,&
      maxit       = 1000,&
      TolFun      = 1e-2_rk,&
      verbosity   = 0)
   call nls%solve(F=F4, x0=[(0.95_rk,0.0_rk) ,(0.95_rk,0.0_rk)], x_sol=x)
   ! check if solution is close to [1,1]
   expected_x = [1.0_rk,1.0_rk]
   call ut%check(real(x,rk), expected_x, 1.0e-1_rk, 'test_solver14' )
   ! call ut%check(x%re, expected_x, 1.0e-1_rk, 'test_solver14' )
end program test_solver14
Call graph
test_solver14 calls check, solve, set_options
newton_complex_step_rel_t0 calls modified_quasi_cs_newton_method_t0, quasi_cs_newton_method_t0
newton_complex_step_rel_t1 calls modified_quasi_cs_newton_method_t1, quasi_cs_newton_method_t1
newton_rel_t0 calls modified_newton_method_t0, modified_quasi_fd_newton_method_t0, newton_method_t0, quasi_fd_newton_method_t0
newton_rel_t1 calls modified_newton_method_t1, modified_quasi_fd_newton_method_t1, newton_method_t1, quasi_fd_newton_method_t1
modified_newton_method_t1 calls solve
modified_quasi_cs_newton_method_t0 calls derivative
modified_quasi_cs_newton_method_t1 calls derivative, solve
modified_quasi_fd_newton_method_t0 calls derivative
modified_quasi_fd_newton_method_t1 calls derivative, solve
newton_method_t1 calls solve
quasi_cs_newton_method_t0 calls derivative
quasi_cs_newton_method_t1 calls derivative, solve
quasi_fd_newton_method_t0 calls derivative
quasi_fd_newton_method_t1 calls derivative, solve
solve calls solver_lin
solver_lin calls gels_rel, gesv_rel
gels_rel calls gels
gesv_rel calls gesv