test_solver8 – ForSolver
test_solver8 Program
14 statements
Source File
Uses
forunittest
forsolver
my_function8
Calls
Variables
Type Attributes Name Initial
type(nlsolver) :: nls
complex(kind=rk) :: x
real(kind=rk) :: expected_x
type(unit_test) :: ut
Source Code
program test_solver8
   use forsolver
   use my_function8
   use forunittest
   implicit none
   type(nlsolver) :: nls
   complex(rk)    :: x
   real(rk)       :: expected_x
   type(unit_test) :: ut
   call nls%set_options(&
      nl_method   = 'newton-quasi-cs-modified',&
      cs_tol      = tiny(0.0_rk),&
      nmp         = 2,&
      maxit       = 100,&
      TolFun      = 1e-6_rk,&
      verbosity   = 0)
   call nls%solve(F=F2, x0=(0.95_rk, 0.0_rk), x_sol=x)
   ! check if solution is close to ~=0.53128
   expected_x = 0.53128_rk
   call ut%check(x%re, 0.53128_rk, 1.0e-4_rk, 'test_solver8' )
end program test_solver8
Call graph
test_solver8 calls check, solve, set_options
newton_complex_step_rel_t0 calls modified_quasi_cs_newton_method_t0, quasi_cs_newton_method_t0
newton_complex_step_rel_t1 calls modified_quasi_cs_newton_method_t1, quasi_cs_newton_method_t1
newton_rel_t0 calls modified_newton_method_t0, modified_quasi_fd_newton_method_t0, newton_method_t0, quasi_fd_newton_method_t0
newton_rel_t1 calls modified_newton_method_t1, modified_quasi_fd_newton_method_t1, newton_method_t1, quasi_fd_newton_method_t1
modified_newton_method_t1 calls solve
modified_quasi_cs_newton_method_t0 calls derivative
modified_quasi_cs_newton_method_t1 calls derivative, solve
modified_quasi_fd_newton_method_t0 calls derivative
modified_quasi_fd_newton_method_t1 calls derivative, solve
newton_method_t1 calls solve
quasi_cs_newton_method_t0 calls derivative
quasi_cs_newton_method_t1 calls derivative, solve
quasi_fd_newton_method_t0 calls derivative
quasi_fd_newton_method_t1 calls derivative, solve
solve calls solver_lin
solver_lin calls gels_rel, gesv_rel
gels_rel calls gels
gesv_rel calls gesv