test_solver6 – ForSolver
test_solver6 Program
BSD 3-Clause
14 statements
Source File
Uses
forunittest
my_function6
forsolver_kinds
forsolver
Calls
Variables
Type Attributes Name Initial
real(kind=rk) :: expected_x
type(nlsolver) :: nls
type(unit_test) :: ut
real(kind=rk) :: x
Source Code
program test_solver6
   use forsolver_kinds, only: rk
   use forsolver, only: nlsolver
   use my_function6, only: F1
   use forunittest, only: unit_test
   implicit none
   type(nlsolver) :: nls
   real(rk)       :: x, expected_x
   type(unit_test) :: ut
   call nls%set_options(&
      nl_method   = 'newton-quasi-fd-modified',&
      fdm_method  = 'central',&
      fdm_tol     = 1e-6_rk,&
      nmp         = 2,&
      maxit       = 100,&
      TolFun      = 1e-4_rk,&
      verbosity   = 0)
   call nls%solve(F=F1, x0=10.0_rk, x_sol=x)
   ! check if solution is close to ~=0.53128
   expected_x = 0.53128_rk
   call ut%check(x, expected_x, 1.0e-4_rk, 'test_solver6' )
end program test_solver6
Call graph
test_solver6 calls check, solve, set_options
newton_complex_step_rel_t0 calls modified_quasi_cs_newton_method_t0, quasi_cs_newton_method_t0
newton_complex_step_rel_t1 calls modified_quasi_cs_newton_method_t1, quasi_cs_newton_method_t1
newton_rel_t0 calls modified_newton_method_t0, modified_quasi_fd_newton_method_t0, newton_method_t0, quasi_fd_newton_method_t0
newton_rel_t1 calls modified_newton_method_t1, modified_quasi_fd_newton_method_t1, newton_method_t1, quasi_fd_newton_method_t1
modified_newton_method_t1 calls solve
modified_quasi_cs_newton_method_t0 calls derivative
modified_quasi_cs_newton_method_t1 calls derivative, solve
modified_quasi_fd_newton_method_t0 calls derivative
modified_quasi_fd_newton_method_t1 calls derivative, solve
newton_method_t1 calls solve
quasi_cs_newton_method_t0 calls derivative
quasi_cs_newton_method_t1 calls derivative, solve
quasi_fd_newton_method_t0 calls derivative
quasi_fd_newton_method_t1 calls derivative, solve
solve calls solver_lin
solver_lin calls gels_rel, gesv_rel
gels_rel calls gels
gesv_rel calls gesv